# Numpy Basics

In [1]:
# install numpy using pip
!pip install numpy

## Importing modules

In [2]:
import numpy as np

## Creating basic arrays

### using np.array()

In [3]:
a = np.array([1,2,3], dtype=int)
print(a)
print(type(a))

b = np.array((1,2,3), dtype=float)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>
[1. 2. 3.]
<class 'numpy.ndarray'>


In [4]:
# two-dimensional array
two_dim_array = np.array([[1,2],[4,5]], dtype=complex)
print('two dimensional array\n', two_dim_array)
print('number of dimensions', two_dim_array.ndim)
print('size of each dimension', two_dim_array.shape)

# three-dimensional array
three_dim_array = np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype=float)
print('three dimensional array\n',three_dim_array)
print('number of dimensions', three_dim_array.ndim)
print('size of each dimension', three_dim_array.shape)

two dimensional array
 [[1.+0.j 2.+0.j]
 [4.+0.j 5.+0.j]]
number of dimensions 2
size of each dimension (2, 2)
three dimensional array
 [[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
number of dimensions 3
size of each dimension (1, 3, 3)


## Important Attributes

**NumPy’s array class is called `ndarray`**

The more important attributes of a ndarray object are:
- ndarray.ndim
- ndarray.shape
- ndarray.size
- ndarray.dtype
- ndarray.itemsize

## Reshape array

In [5]:
a = np.arange(9)
print(a)
a = np.reshape(a, newshape=(3,3))
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Sorting

In [6]:
a = np.array([10, 25, 30, 5, 50])
a = np.sort(a)
print(a)

[ 5 10 25 30 50]


## Concatenation

In [7]:
a = np.arange(10, 51, 5)
print(a)
b = np.arange(60, 121, 10)
print(b)
c = np.concatenate((a,b))
print(c)

[10 15 20 25 30 35 40 45 50]
[ 60  70  80  90 100 110 120]
[ 10  15  20  25  30  35  40  45  50  60  70  80  90 100 110 120]


## Mean

In [8]:
a = np.array([1,2,3])
print(a.mean())
b = np.arange(9).reshape(3,3)
print(b)
print(b.mean())

2.0
[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0


In [9]:
a = np.arange(1,5).reshape(2,2)
print(a)
print(a.mean())

[[1 2]
 [3 4]]
2.5
