# Numpy Basics

In [12]:
# install numpy using pip
!pip install numpy

## Importing modules

In [9]:
import numpy as np

## Creating basic arrays

### using np.array()

In [18]:
a = np.array([1,2,3], dtype=int)
print(a)
print(type(a))

b = np.array((1,2,3), dtype=float)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>
[1. 2. 3.]
<class 'numpy.ndarray'>


In [38]:
# two dimensional array
two_dim_array = np.array([[1,2],[4,5]], dtype=int)
print('two dimensional array\n', two_dim_array)
print('number of dimensions', two_dim_array.ndim)
print('size of each dimension', two_dim_array.shape)

# three dimensional array
three_dim_array = np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype=float)
print('three dimensional array\n',three_dim_array)
print('number of dimensions', three_dim_array.ndim)
print('size of each dimension', three_dim_array.shape)

two dimensional array
 [[1 2]
 [4 5]]
number of dimensions 2
size of each dimension (2, 2)
three dimensional array
 [[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
number of dimensions 3
size of each dimension (1, 3, 3)
