# Basics of Matrices

## Importing modules

In [1]:
import numpy as np

## Basic Matrix creation

In [2]:
# using numpy.matrix
a = np.matrix('1,2; 3,4')
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
2
(2, 2)


In [3]:
# using numpy.matrix
b = np.matrix('1, 2, 3; 4, 5, 6; 7,8,9')
print(b)
print(type(b))
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
2
(3, 3)


In [4]:
# using numpy.array
arr_a = np.array([1, 2, 3, 4]).reshape(2,2)
print(arr_a)
print(type(arr_a))
# converting numpy.array to numpy.matrix
matrix_a = np.asmatrix(arr_a)
print(matrix_a)
print(type(matrix_a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [5]:
array_a = np.zeros(5, dtype=int)
print(array_a)
array_b = np.zeros((2,2), dtype=int)
print(array_b)
array_c = np.ones(9, dtype=complex).reshape(3,3)
print(array_c)

[0 0 0 0 0]
[[0 0]
 [0 0]]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [6]:
x = np.random.rand(2,2)
print(x)
print(x.shape)
print(type(x))
y = np.asmatrix(x)
print(y)
print(type(y))

[[0.01406774 0.68738552]
 [0.99228243 0.42909045]]
(2, 2)
<class 'numpy.ndarray'>
[[0.01406774 0.68738552]
 [0.99228243 0.42909045]]
<class 'numpy.matrix'>


In [7]:
x = np.arange(8).reshape(2,4)
print(x)
y = np.arange(20, 30).reshape(2,5)
print(y)
z = np.arange(1, 50, 5)
print(z)
print(np.reshape(z, (5,2)))

[[0 1 2 3]
 [4 5 6 7]]
[[20 21 22 23 24]
 [25 26 27 28 29]]
[ 1  6 11 16 21 26 31 36 41 46]
[[ 1  6]
 [11 16]
 [21 26]
 [31 36]
 [41 46]]
